stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - src/data/data_collection.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_prep.py
    deps:
    - data/raw
    - src/data/data_prep.py
    outs:
    - data/processed
  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/processed
    - src/models/model_building.py
    outs:
    - results/model.pkl
  model_evaluation:
    cmd: python src/models/model_eval.py
    deps:
    - data/processed
    - src/models/model_eval.py
    - results/model.pkl
    outs:
    - reports/metrics_rfc.json    